# fly.toml app configuration file generated for chirper-gu44ia on 2024-11-05T22:28:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chirper-gu44ia'
primary_region = 'ams'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  APP_NAME=Chirper
  APP_ENV=local
  APP_KEY=base64:wK2XxeTmtd0EQZLnW73HR1xuM1d4cAdCm+7KHfzGkvA=
  APP_DEBUG=true
  APP_TIMEZONE=UTC
  APP_URL=http://chirper.test
  APP_LOCALE=en
  APP_FALLBACK_LOCALE=en
  APP_FAKER_LOCALE=en_US
  APP_MAINTENANCE_DRIVER=file
  BCRYPT_ROUNDS=12
  LOG_CHANNEL=stack
  LOG_STACK=single
  LOG_DEPRECATIONS_CHANNEL=null
  LOG_LEVEL=debug
  DB_CONNECTION=mysql
  DB_HOST=159.69.147.64
  DB_PORT=5432
  DB_DATABASE=chirper
  DB_USERNAME=mysql
  DB_PASSWORD=YIulU8efa7hIoulwkbCkRDQ2eIcjhu0of4yQer0y1hWxlDbCa1KLartEVv30tuwz
  SESSION_DRIVER=database
  SESSION_LIFETIME=120
  SESSION_ENCRYPT=false
  SESSION_PATH=/
  SESSION_DOMAIN=null
  BROADCAST_CONNECTION=log
  FILESYSTEM_DISK=local
  QUEUE_CONNECTION=database
  CACHE_STORE=database
  VITE_APP_NAME="${APP_NAME}"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
